### ISSUE TITLE
部署报错

### ISSUE THREAD

**Issue by wuhang2003** [Aoang/TSCT#3]
在 Vercel 中填完对应变量之后部署出现问题，如下图
![](https://i.loli.net/2021/02/17/dnqt7kbOjfSi54A.png)
`import` 的那个链接需要修改成自己项目的么

**Comment by Aoang** [comment]
看了看 Vercel 的部署日志，可能是 go mod 导致的问题。

你可以根据 Vercel 的规范，直接复制这个文件的内容至 Serverless 项目


https://github.com/Aoang/TSCT/blob/455613978b96368f3da226cbd75d371f3eeebc4d/api/tsct.go

**Comment by wuhang2003** [comment]
具体复制到哪里呢，function 那边因为部署失败无法填，麻烦大佬截个图指点一下

**Comment by Aoang** [comment]
测试了下，已经可以了。

pull 一下，或者删除原有库之后重新 fork，然后根据文档部署。

现在文档和之前比较，多了一项：在 Vercel 面板导入 git 库，部署目录选择 vercel
